eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: tslist
  rabbitmq:
    host: 192.168.1.202
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
  sleuth:
      sampler:
          percentage: 1.0
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
