eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: zuulgateweay
zuul:
  routes:
    api:
      path: /api/**
      serviceId: tslist
